### ISSUE TITLE
Can we do papers OCR ready?

### ISSUE THREAD

**Issue by kalismeras61** [sawankumarbundelkhandi/edge_detection#1]
Hello, 
I tested this plugins, it's detect everything  i just want to detect paper, because if have square in paper it detects firs square :) so i just want to detect paper like WeScan and second  is when detect paper i want to change it black & white  and heigh resolution for OCR ready.

Can you give suggestion?

**Comment by sawankumarbundelkhandi** [comment]
This is implemented in both Android and iOS. You can change the image to black and white. 
Please try 1.0.7 from the pub.dev
