### ISSUE TITLE
Android 12 Build Failed 

### ISSUE THREAD

**Issue by xhayankhan** [sawankumarbundelkhandi/edge_detection#101]
Failure [-127: Package com.sample.edgedetectionexample attempting to declare permission android.permission.FLASHLIGHT in non-existing group android.permission-group.HARDWARE_CONTROLS]

**Comment by sawankumarbundelkhandi** [comment]
please have a look at this - https://stackoverflow.com/a/70665782.

I will also make the changes in the plugin.
