### ISSUE TITLE
pressing save button more than once

### ISSUE THREAD

**Issue by AhmadHusein5853** [sawankumarbundelkhandi/edge_detection#103]
**FATAL EXCEPTION**
by pressing the save button more than one time (very quick)

![grafik](https://user-images.githubusercontent.com/74105989/190540130-18e8850e-9928-462e-862e-29b25395021a.png)

**Comment by AhmadHusein5853** [comment]
a fix for this could be by adding this line

```
item.setEnabled(false)
```

in "CropActivity.kt"   


![grafik](https://user-images.githubusercontent.com/74105989/190666373-b1f5e902-143d-4242-ac8c-b6dbcc60f66a.png)

**Comment by sawankumarbundelkhandi** [comment]
@AhmadHusein5853 can you do a PR please?
