### ISSUE TITLE
Add a separate method for gallery pictures

### ISSUE THREAD

**Issue by UlanNurmatov** [sawankumarbundelkhandi/edge_detection#108]
Currently pictures from gallery can be chosen from camera view.
Can you add a separate method which lets you pick a picture from gallery without opening a camera? 
Something like **EdgeDetection.detectEdgeFromGallery;**

**Comment by sawankumarbundelkhandi** [comment]
@rsanjuan87 has already implemented it here https://github.com/sawankumarbundelkhandi/edge_detection/pull/90

Can you please try this code?

https://github.com/sawankumarbundelkhandi/edge_detection/pull/90#issuecomment-1236291986
