### ISSUE TITLE
ios select gallery image crop has error

### ISSUE THREAD

**Issue by giroskii** [sawankumarbundelkhandi/edge_detection#109]
When you run the git example file, an error appears when you select a picture in the gallery.
Android has not been tested.

The code in Pub.dev works.

```
The following FileSystemException was thrown resolving an image codec:
Cannot open file, path = '/var/mobile/Containers/Data/Application/10A55998-891A-47DB-B98D-CCA0BAEC312E/Library/Application Support/1668071559.jpeg' (OS Error: No such file or directory, errno = 2)

When the exception was thrown, this was the stack
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
<asynchronous suspension>
#1      FileImage._loadAsync
package:flutter/…/painting/image_provider.dart:994
<asynchronous suspension>
Path: /var/mobile/Containers/Data/Application/10A55998-891A-47DB-B98D-CCA0BAEC312E/Library/Application Support/1668071559.jpeg
```

**Comment by knottx** [comment]
@sawankumarbundelkhandi  i've got this problem too, for camera is work fine. do you have an advice.

**Comment by QPAYRE** [comment]
Same here

**Comment by QPAYRE** [comment]
> @sawankumarbundelkhandi i've got this problem too, for camera is work fine. do you have an advice.

Hey ! Did you find a solution ?

**Comment by rsanjuan87** [comment]
same bug
https://github.com/sawankumarbundelkhandi/edge_detection/issues/120

**Comment by rsanjuan87** [comment]
@sawankumarbundelkhandi remember to close this, and delete this comment
