### ISSUE TITLE
Does not specify a Swift version

### ISSUE THREAD

**Issue by os20** [sawankumarbundelkhandi/edge_detection#11]
Hello,

after embedding the plugin into my project I get the error message:

**Unable to determine Swift version for the following pods:
    - `edge_detection` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.**

How can the error be corrected?

**Comment by sawankumarbundelkhandi** [comment]
I have fixed this bug. I will soon publish it.

Please test and confirm if it works.

**Comment by sawankumarbundelkhandi** [comment]
I have just published a new version v1.0.5.
Please try it and let me know if you are still facing the same issue.
