### ISSUE TITLE
NullPointerException by scanActivity

### ISSUE THREAD

**Issue by AhmadHusein5853** [sawankumarbundelkhandi/edge_detection#117]
E/AndroidRuntime(31003): FATAL EXCEPTION: main
E/AndroidRuntime(31003): Process: com.sample.edgedetectionexample, PID: 31003
E/AndroidRuntime(31003): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sample.edgedetectionexample/com.sample.edgedetection.scan.ScanActivity}: java.lang.NullPointerException: null cannot be cast to non-null type kotlin.String
E/AndroidRuntime(31003): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4166)
E/AndroidRuntime(31003): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4312)
E/AndroidRuntime(31003): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
E/AndroidRuntime(31003): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(31003): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(31003): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2571)
E/AndroidRuntime(31003): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(31003): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(31003): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(31003): 	at android.app.ActivityThread.main(ActivityThread.java:8741)
E/AndroidRuntime(31003): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31003): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(31003): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
E/AndroidRuntime(31003): Caused by: java.lang.NullPointerException: null cannot be cast to non-null type kotlin.String
E/AndroidRuntime(31003): 	at com.sample.edgedetection.scan.ScanActivity.prepare(ScanActivity.kt:67)
E/AndroidRuntime(31003): 	at com.sample.edgedetection.base.BaseActivity.onCreate(BaseActivity.kt:21)
E/AndroidRuntime(31003): 	at android.app.Activity.performCreate(Activity.java:8578)
E/AndroidRuntime(31003): 	at android.app.Activity.performCreate(Activity.java:8557)
E/AndroidRuntime(31003): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
E/AndroidRuntime(31003): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4147)
E/AndroidRuntime(31003): 	... 12 more
I/Process (31003): Sending signal. PID: 31003 SIG: 9

**Comment by rsanjuan87** [comment]
To resolve this error I had to set the dependency to the repo in pubspec.yaml
```
  edge_detection:
    git: https://github.com/sawankumarbundelkhandi/edge_detection.git
```

**Comment by achalkias** [comment]
> To resolve this error I had to set the dependency to the repo in pubspec.yaml Even to this date
> 
> ```
>   edge_detection:
>     git: https://github.com/sawankumarbundelkhandi/edge_detection.git
> ```

But this way the aab becomes very big on size mine went from 33mb to 128mb
