### ISSUE TITLE
Attribute application@theme value=(@style/AppTheme)

### ISSUE THREAD

**Issue by os20** [sawankumarbundelkhandi/edge_detection#12]
Hello,
I have the following problem:
When I integrate the plugin I get the error message:

```
_Attributes application@theme value=(@style/AppTheme) from [:edge_detection] AndroidManifest.xml:13:9-40
	is also present at [:flutter_barcode_scanner]_
```

The solution offered:

`Suggestion: add 'tools:replace="android:theme"' to <application> element at AndroidManifest.xml:16:5-45:19 to override`

doesn't work.

How can I fix the problem?

**Comment by RaiKhurram** [comment]
E:\RamSolutionBackup\remasmith\android\app\src\debug\AndroidManifest.xml:13:9-40 Error:
	Attribute application@theme value=(@style/AppTheme) from [:edge_detection] AndroidManifest.xml:13:9-40
	is also present at [:stripe_payment] AndroidManifest.xml:11:18-74 value=(@style/Theme.AppCompat.Light.NoActionBar).
	Suggestion: add 'tools:replace="android:theme"' to <application> element at AndroidManifest.xml:10:5-42:19 to override.
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by RaiKhurram** [comment]
i am facing same problem.
E:\RamSolutionBackup\remasmith\android\app\src\debug\AndroidManifest.xml:13:9-40 Error:
	Attribute application@theme value=(@style/AppTheme) from [:edge_detection] AndroidManifest.xml:13:9-40
	is also present at [:stripe_payment] AndroidManifest.xml:11:18-74 value=(@style/Theme.AppCompat.Light.NoActionBar).
	Suggestion: add 'tools:replace="android:theme"' to <application> element at AndroidManifest.xml:10:5-42:19 to override.
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by sawankumarbundelkhandi** [comment]
If it's open-source can you send me the repo link?

**Comment by Gramatton** [comment]
Locate and edit your main AndroidManifest.xml file `android/app/src/main/AndroidManifest.xml`

1. Add this line `xmlns:tools="http://schemas.android.com/tools"` to the root **manifest** tag
2. Add these two lines `android:theme="@style/AppTheme"` and `tools:replace="android:theme"` to the **application** tag

In result, you will have the following AndroidManifest.xml:
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.doitcare.app"
    xmlns:tools="http://schemas.android.com/tools">
    <application
        tools:replace="android:theme"
        android:theme="@style/AppTheme"
        ...>
        <activity
            ...
        </activity>
    </application>
</manifest>
```

**Comment by sawankumarbundelkhandi** [comment]
closing as someone answered on StackOverflow as well - https://stackoverflow.com/a/66710028/5149803
