### ISSUE TITLE
Detects edge properly when capturing and giving wrong edges after capture 

### ISSUE THREAD

**Issue by Appstute-Prerna** [sawankumarbundelkhandi/edge_detection#131]
when I initiate camera for scanning it gives me correct edges before capture clicked. When I click on capture and comes on crop screen the auto detected edges are always showing wrong.

**Comment by sawankumarbundelkhandi** [comment]
possible duplicate of https://github.com/sawankumarbundelkhandi/edge_detection/issues/83
