### ISSUE TITLE
Android app crash when selecting image directly from the gallery via detectEdgeFromGallery method

### ISSUE THREAD

**Issue by Gidzkid** [sawankumarbundelkhandi/edge_detection#133]
When i tried to select image directly from the gallery, i encounter  null pointer exception.  I can't pass scan title into detectEdgeFromGallery method and the following code trying to get scan title in ScanActivity.prepare() method. 

`this.title = initialBundle.getString(EdgeDetectionHandler.SCAN_TITLE) as String `

**My code**
```
bool success = await EdgeDetection.detectEdgeFromGallery(
        imagePath,
        androidCropTitle: 'Crop', // use custom localizations for android
        androidCropBlackWhiteTitle: 'Black White',
        androidCropReset: 'Reset',
      );
```

**Exception encounter**

> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app.cardpro.cardpro_flutter/com.sample.edgedetection.scan.ScanActivity}: java.lang.NullPointerException: null cannot be cast to non-null type kotlin.String
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3594)
>         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
>         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
>         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loop(Looper.java:223)
>         at android.app.ActivityThread.main(ActivityThread.java:7698)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
>      Caused by: java.lang.NullPointerException: null cannot be cast to non-null type kotlin.String
>         at com.sample.edgedetection.scan.ScanActivity.prepare(ScanActivity.kt:67)
>         at com.sample.edgedetection.base.BaseActivity.onCreate(BaseActivity.kt:21)
>         at android.app.Activity.performCreate(Activity.java:8000)
>         at android.app.Activity.performCreate(Activity.java:7984)
>         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3403)

**Comment by achalkias** [comment]
Same problem unfortunately same error same everything the only solution is to load the plugin from git but it makes the aab file enormously big

**Comment by sawankumarbundelkhandi** [comment]
This issue is fixed. Please check it on latest version v1.1.2 on pub. 
Please download the package from there and make sure to follow the ReadMe.
