### ISSUE TITLE
cant  use with  org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.31

### ISSUE THREAD

**Issue by PrzemyslawPluszowy** [sawankumarbundelkhandi/edge_detection#136]
* What went wrong:
The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher.
The following dependencies do not satisfy the required version:
root project 'android' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.31

**Comment by CikaTom** [comment]
Set version to this:
`ext.kotlin_version = '1.8.0'
`
As it is describedd on Android section of readme

**Comment by S1mple133** [comment]
I get a similar exception. My kotlin_version is 1.8.0. I see that the gradle version was updated 2 hrs ago in this [commit](https://github.com/sawankumarbundelkhandi/edge_detection/commit/d168ca22dbd6f0ada122538dee039da36e5fef54). Maybe the newest commit is not included in the 1.1.1 version on the pub.dev package repository?

`project ':edge_detection' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.31`
