### ISSUE TITLE
Edge detection is already active error.

### ISSUE THREAD

**Issue by 3rsin3rgul** [sawankumarbundelkhandi/edge_detection#140]
Hello,
I am receiving this error constantly.  It's Android API 30.

![Screenshot 2023-07-17 at 12 02 36](https://github.com/sawankumarbundelkhandi/edge_detection/assets/25375440/d6a9d2c7-d931-4e1b-bac5-50e42e9d4d43)

**Comment by ChristophRoess** [comment]
Having the same issue, could you please support?

**Comment by 3rsin3rgul** [comment]
I am also receiving this error on Api 33 Emulator. 

`D/OpenCV/StaticHelper( 8416): Trying to get library list
E/OpenCV/StaticHelper( 8416): OpenCV error: Cannot load info library for OpenCV
D/OpenCV/StaticHelper( 8416): Library list: ""
D/OpenCV/StaticHelper( 8416): First attempt to load libs
D/OpenCV/StaticHelper( 8416): Trying to init OpenCV libs
D/OpenCV/StaticHelper( 8416): Trying to load library opencv_java3
D/OpenCV/StaticHelper( 8416): Cannot load library "opencv_java3"
W/System.err( 8416): java.lang.UnsatisfiedLinkError: dlopen failed: library "libopencv_java3.so" not found
W/System.err( 8416): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
W/System.err( 8416): 	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
W/System.err( 8416): 	at java.lang.System.loadLibrary(System.java:1661)
W/System.err( 8416): 	at org.opencv.android.StaticHelper.loadLibrary(StaticHelper.java:64)
W/System.err( 8416): 	at org.opencv.android.StaticHelper.initOpenCVLibs(StaticHelper.java:95)
W/System.err( 8416): 	at org.opencv.android.StaticHelper.initOpenCV(StaticHelper.java:39)
W/System.err( 8416): 	at org.opencv.android.OpenCVLoader.initDebug(OpenCVLoader.java:102)
W/System.err( 8416): 	at com.sample.edgedetection.scan.ScanActivity.prepare(ScanActivity.kt:41)
W/System.err( 8416): 	at com.sample.edgedetection.base.BaseActivity.onCreate(BaseActivity.kt:20)
W/System.err( 8416): 	at android.app.Activity.performCreate(Activity.java:8305)
W/System.err( 8416): 	at android.app.Activity.performCreate(Activity.java:8284)
W/System.err( 8416): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
W/System.err( 8416): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
W/System.err( 8416): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
W/System.err( 8416): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
W/System.err( 8416): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
W/System.err( 8416): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
W/System.err( 8416): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
W/System.err( 8416): 	at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err( 8416): 	at android.os.Looper.loopOnce(Looper.java:201)
W/System.err( 8416): 	at android.os.Looper.loop(Looper.java:288)
W/System.err( 8416): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
W/System.err( 8416): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 8416): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
W/System.err( 8416): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
D/OpenCV/StaticHelper( 8416): First attempt to load libs fails
I/ScanActivity( 8416): loading opencv error, exit
D/CompatibilityChangeReporter( 8416): Compat change id reported: 78294732; UID 10159; state: ENABLED`
