### ISSUE TITLE
 lib not working on flutter build  android-arm

### ISSUE THREAD

**Issue by Vanilla1999** [sawankumarbundelkhandi/edge_detection#143]
I added a dependency to pubspec.yaml edge_detection: ^1.1.2

flutter build apk --release --target-platform=android-arm -  apk not working 

Inside the repository, there are the necessary files in the jni Lib s folder, but not in pub.dev

![image](https://github.com/sawankumarbundelkhandi/edge_detection/assets/41183994/8543b5a4-ab86-4567-90d8-3dca71da2c64)

**Comment by sawankumarbundelkhandi** [comment]
I have only pushed arm64-v8a and armeabi-v7a to the public repository due to Dart package limitations of 100 MB. If you require android-arm, you can install it using the GitHub URL in the dependencies.
