### ISSUE TITLE
Xcode 15 - Stored properties cannot be marked unavailable with '@available'

### ISSUE THREAD

**Issue by ufukhawk** [sawankumarbundelkhandi/edge_detection#151]
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.5, on macOS 13.6 22G120 darwin-arm64, locale en-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.81.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

```

```
Swift Compiler Error (Xcode): Stored properties cannot be marked unavailable with '@available'
/.../ios/Pods/WeScan/WeScan/ImageScannerController.swift:196:5

Swift Compiler Error (Xcode): Stored properties cannot be marked unavailable with '@available'
/.../ios/Pods/WeScan/WeScan/ImageScannerController.swift:199:5

Swift Compiler Error (Xcode): Stored properties cannot be marked unavailable with '@available'
/.../ios/Pods/WeScan/WeScan/ImageScannerController.swift:202:5

Swift Compiler Error (Xcode): Stored properties cannot be marked unavailable with '@available'
/.../ios/Pods/WeScan/WeScan/ImageScannerController.swift:205:5

Uncategorized (Xcode): Command SwiftCompile failed with a nonzero exit code

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro Max.
```

**Comment by jusuf-el** [comment]
I am having the same problem...

**Comment by giapnhgc** [comment]
Instead of complaining, we can find out the cause and read other issues to see if there are any solutions.
Try using this temporarily to see if it works.

I forked and tried it for my project and it worked when building on xCode 15.
If it works, please use it temporarily until the author updates the new version.
[Link here](https://github.com/sawankumarbundelkhandi/edge_detection/issues/146#issuecomment-1733009468)

**Comment by sawankumarbundelkhandi** [comment]
@ufukhawk  @jusuf-el please let me know if  @giapnhgc implementation is working follow this comment from here - 

https://github.com/sawankumarbundelkhandi/edge_detection/issues/146#issuecomment-1733009468

@giapnhgc thanks for all the work you have done.

**Comment by ufukhawk** [comment]
> Instead of complaining, we can find out the cause and read other issues to see if there are any solutions. Try using this temporarily to see if it works.
> 
> I forked and tried it for my project and it worked when building on xCode 15. If it works, please use it temporarily until the author updates the new version. [Link here](https://github.com/sawankumarbundelkhandi/edge_detection/issues/146#issuecomment-1733009468)
> 
> Hope it helps you. Good luck!

You right, I will try.

**Comment by ufukhawk** [comment]
Solved. Thanks @giapnhgc

**Comment by ufukhawk** [comment]
Ahh, project run with Debug mode. but when i archive for publishing getting this error : 

B/BL out of range 135289540 (max +/-128MB) to ''

Linker command failed with exit code 1 (use -v to see invocation)

**Comment by ufukhawk** [comment]
Yes Solved. Thanks. @sawankumarbundelkhandi

**Comment by sawankumarbundelkhandi** [comment]
@ufukhawk so you have tested @giapnhgc work right and it's working in both debug and release mode.
