### ISSUE TITLE
Building apk

### ISSUE THREAD

**Issue by mosi2142** [sawankumarbundelkhandi/edge_detection#157]
When building apk while having this package, size of my app turned from 25 megabyte to 84 megabytes.
this is definitely not normal.

**Comment by sawankumarbundelkhandi** [comment]
@mosi2142 which version of plugin are you using?

**Comment by mosi2142** [comment]
> @mosi2142 which version of plugin are you using?

edge_detection: ^1.1.3

**Comment by mosi2142** [comment]
when i usually building fat apk my app usually will be between 24-26 megabyte,
but after using this package and build fat apk my apk is 84.4 megabyte!!!.
if i remove the package and then build again, app size size will be around 24-26 megabytes again.

even if i build with abi split, my app-arm64-v8a will get 16.3 megabyte.
and app-armeabi-v7a will get 15.1 megabyte.
and app-x86_64 will be 38.7 megabyte!!!

**Comment by sawankumarbundelkhandi** [comment]
It's expected for the app size to increase when using OpenCV

https://github.com/ramonrabello/opencv-android?tab=readme-ov-file#shrinking-the-release-apk-size
https://stackoverflow.com/questions/44962460/how-to-reduce-the-apk-size-of-android-app-which-need-opencv-lib-only-for-image
https://stackoverflow.com/questions/42904912/opencv-android-apk-is-huge

**Comment by sawankumarbundelkhandi** [comment]
@mosi2142 please close it if my above comment helped/clarified you in any way.
