### ISSUE TITLE
MissingPluginException(No implementation found for method edge_detect on channel edge_detection)

### ISSUE THREAD

**Issue by surajprasad57** [sawankumarbundelkhandi/edge_detection#16]
Hello 
 we are getting  MissingPluginException  when we execute below given code 

`try {
      imagePath = await EdgeDetection.detectEdge;
    } on PlatformException  catch (e) {
      print(e.toString());
    } on Exception catch (e) {
      print(e.toString());
    }`

we added entry of edge_detection library into pubspec.yml file as given below 

` edge_detection: ^1.0.4
 `
one thing we noticed that  when we add this `file_picker: ^1.3.8` file_picker library with edge_detection  then its throwing above exception. we unable to rectify this issue why its  stoped working. so please help me out 
 
Thanks

**Comment by sawankumarbundelkhandi** [comment]
@surajprasad57 If it's open-source can you send me the repo link?

**Comment by xascis** [comment]
Same problem. If you have file_picker and edge_detect in the same app, file_picker doesn't work properly.

This is how I fixed: https://github.com/xascis/edge_detection/commit/7b4a3f064fe962cb38a6d216db0847dddf900ab9

**Comment by sawankumarbundelkhandi** [comment]
@xascis @surajprasad57 I am unable to recreate the issue. If you can please share a sample repo then I will fix it.

**Comment by xascis** [comment]
Just add 'file_picker: ^1.4.3+2' into your project with 'edge_detection'.
Put each one in one button. 
And file_picker will not work on Android.

I needed both plugins to let the user to choose between uploading a file from the device (file_picker) or taking a picture (edge_detection)

**Comment by sawankumarbundelkhandi** [comment]
This is fixed in https://github.com/sawankumarbundelkhandi/edge_detection/pull/18

Thanks to @RodrigoPorras and @xascis 

I will release it on pub soon

**Comment by sawankumarbundelkhandi** [comment]
I have just published a new version v1.0.5.
Please try it and let me know if you are still facing the same issue.
