### ISSUE TITLE
android build failed #Execution failed for task ':edge_detection:compileDebugKotlin'.

### ISSUE THREAD

**Issue by dihsarjr** [sawankumarbundelkhandi/edge_detection#164]
* What went wrong:
Execution failed for task ':edge_detection:compileDebugKotlin'.
> 'compileDebugJavaWithJavac' task (current target is 1.8) and 'compileDebugKotlin' task (current target is 17) jvm target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain

**Comment by sinanhaci** [comment]
Did you solve this problem?

**Comment by dihsarjr** [comment]
yes after adding this

    tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
        kotlinOptions {
            jvmTarget = "1.8"
        }
    }
