### ISSUE TITLE
Edge Detection Library Fails to Compile for iOS Swift (WeScan)

### ISSUE THREAD

**Issue by TheArchitect123** [sawankumarbundelkhandi/edge_detection#173]
This is a duplicate of a closed issue. It looks like this issue is still there.

https://github.com/sawankumarbundelkhandi/edge_detection/issues/155

**Comment by TheArchitect123** [comment]
@sawankumarbundelkhandi

**Comment by TheArchitect123** [comment]
OK, sorry there was just some documentation for Xcode 15 I missed. All good now

**Comment by SamadDev** [comment]
pod 'WeScan', :path => '.symlinks/plugins/edge_detection/ios/WeScan-3.0.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  pod 'WeScan', :path => '.symlinks/plugins/edge_detection/ios/WeScan-3.0.0'
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
