### ISSUE TITLE
File not found exception

### ISSUE THREAD

**Issue by xbadal** [sawankumarbundelkhandi/edge_detection#28]
I Run the example of this repo and i found file not found exception.

Caused by: java.io.FileNotFoundException: /storage/emulated/0/smart_scanner/crop_1125.jpeg: open failed: EACCES (Permission denied)

**Comment by 3rsin3rgul** [comment]
> I Run the example of this repo and i found file not found exception.
> 
> Caused by: java.io.FileNotFoundException: /storage/emulated/0/smart_scanner/crop_1125.jpeg: open failed: EACCES (Permission denied)

Hello,
You need to add permission for android devices. Try to search for permission handler for flutter on google.

**Comment by parth0078** [comment]
File not found exception occur in IOS Please help

**Comment by sawankumarbundelkhandi** [comment]
@parth0078 @xbadal Use this plugin before calling Edge detection - https://pub.dev/packages/permission_handler

Check for Camera and Storage permission and if not granted don't call the Edge detection.

**Comment by parth0078** [comment]
hi @sawankumarbundelkhandi  I added following permission in info.plist for IOS .
<key>NSCameraUsageDescription</key>
    <string>Allow to use camera</string>
    <key>NSPhotoLibraryUsageDescription</key>
    <string>Allow to use media</string>

again same Error occur

**Comment by sawankumarbundelkhandi** [comment]
@xbadal check this - https://stackoverflow.com/a/57804657/5149803
