### ISSUE TITLE
Pick from gallery!

### ISSUE THREAD

**Issue by 3rsin3rgul** [sawankumarbundelkhandi/edge_detection#29]
Hello,
I am trying to implement gallery scan option and I made it for iOS version but I am having hard time for Android. Can anyone help me about this? @BugsBunnyBR  @y-okady  @RodrigoPorras  @sawankumarbundelkhandi 
Thanks.

**Comment by y-okady** [comment]
@3rsin3rgul 
Hello. Unfortunately I don't use this library for Android. I hope everything will go well!

**Comment by ameeee** [comment]
@3rsin3rgul did you find a solution to pick image from gallery and apply an edge detection on it? I

**Comment by 3rsin3rgul** [comment]
> @3rsin3rgul did you find a solution to pick image from gallery and apply an edge detection on it? I

I created my own plugin. The author not responding to anything.

**Comment by ameeee** [comment]
@3rsin3rgul can you share it?
