### ISSUE TITLE
I couldn't find he plugin in pub.dev?

### ISSUE THREAD

**Issue by NTMS2017** [sawankumarbundelkhandi/edge_detection#3]
Thanks for great plugin, but I couldn't find plugin in pub.dev. When you gonna publish in pub.dev? Thank you

**Comment by edismooth** [comment]
You can install that plugin directly from gitgub. You have to add in your pubspec.yam file (in dependencies part):

```
  edge_detection:
    git: https://github.com/sawankumarbundelkhandi/edge_detection.git
```

**Comment by sawankumarbundelkhandi** [comment]
I have published it here - https://pub.dev/packages/edge_detection

**Comment by limajr** [comment]
Hi Sawan, thanks for the nice work here. I tried - until now without success - to update the plugin to androidx compatibility. Do you think it is possible?

**Comment by kalismeras61** [comment]
> Hi Sawan, thanks for the nice work here. I tried - until now without success - to update the plugin to androidx compatibility. Do you think it is possible?

Some one did this. You can look pull request.

**Comment by sawankumarbundelkhandi** [comment]
Updated the code. I will publish it soon.
