### ISSUE TITLE
iPadOS widget is not taking whole screen

### ISSUE THREAD

**Issue by CellCS** [sawankumarbundelkhandi/edge_detection#32]
In iPadOS, interface is not taking correct screen size.

Test in iphone 7plus, has no this issue.  

For iPadOS, whether this issue may come from WeScan? thanks.

![IMG_0026](https://user-images.githubusercontent.com/16886624/93526187-17f05300-f905-11ea-9891-646518fcf50d.PNG)

![IMG_0027](https://user-images.githubusercontent.com/16886624/93526191-19218000-f905-11ea-9947-b3eda77880b7.PNG)

**Comment by sawankumarbundelkhandi** [comment]
@CellCS can you check if setting this works for you?

https://github.com/honzakeller/edge_detection/blob/master/ios/Classes/HomeViewController.swift#L14

**Comment by CellCS** [comment]
Hi @sawankumarbundelkhandi 

 👍wonderful!!! Solved.  Tested by iPad 6th iPadOS 14.4.2.  

Thanks
