### ISSUE TITLE
Saving picture fails on Android 10+ 

### ISSUE THREAD

**Issue by nikolaychernov** [sawankumarbundelkhandi/edge_detection#38]
As described in #33, saving a picture on Android results in 

> E/AndroidRuntime(21257): FATAL EXCEPTION: main
E/AndroidRuntime(21257): Process: com.ome.dietgene.dev, PID: 21257
E/AndroidRuntime(21257): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(21257): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
E/AndroidRuntime(21257): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/AndroidRuntime(21257): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(21257): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21257): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/AndroidRuntime(21257): 	... 1 more
E/AndroidRuntime(21257): Caused by: java.io.FileNotFoundException: /storage/emulated/0/smart_scanner/crop_16732.jpeg: open failed: EACCES (Permission denied)
E/AndroidRuntime(21257): 	at libcore.io.IoBridge.open(IoBridge.java:496)
E/AndroidRuntime(21257): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
E/AndroidRuntime(21257): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
E/AndroidRuntime(21257): 	at com.sample.edgedetection.crop.CropPresenter.save(CropPresenter.kt:129)
E/AndroidRuntime(21257): 	at com.sample.edgedetection.crop.CropActivity.onOptionsItemSelected(CropActivity.kt:55)
E/AndroidRuntime(21257): 	at android.app.Activity.onMenuItemSelected(Activity.java:4155)
E/AndroidRuntime(21257): 	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:384)
E/AndroidRuntime(21257): 	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)
E/AndroidRuntime(21257): 	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
E/AndroidRuntime(21257): 	at androidx.appcompat.app.AppCompatDelegateImpl.onMenuItemSelected(AppCompatDelegateImpl.java:1030)
E/AndroidRuntime(21257): 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
E/AndroidRuntime(21257): 	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
E/AndroidRuntime(21257): 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
E/AndroidRuntime(21257): 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:981)
E/AndroidRuntime(21257): 	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
E/AndroidRuntime(21257): 	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
E/AndroidRuntime(21257): 	at android.view.View.performClick(View.java:7201)
E/AndroidRuntime(21257): 	at android.view.View.performClickInternal(View.java:7170)
E/AndroidRuntime(21257): 	at android.view.View.access$3500(View.java:806)
E/AndroidRuntime(21257): 	at android.view.View$PerformClick.run(View.java:27582)
E/AndroidRuntime(21257): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(21257): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(21257): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(21257): 	at android.app.ActivityThread.main(ActivityThread.java:7710)
E/AndroidRuntime(21257): 	... 3 more
E/AndroidRuntime(21257): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
E/AndroidRuntime(21257): 	at libcore.io.Linux.open(Native Method)
E/AndroidRuntime(21257): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
E/AndroidRuntime(21257): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
E/AndroidRuntime(21257): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
E/AndroidRuntime(21257): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7609)
E/AndroidRuntime(21257): 	at libcore.io.IoBridge.open(IoBridge.java:482)
E/AndroidRuntime(21257): 	... 26 more

because of [https://developer.android.com/training/data-storage#scoped-storage](url).

Google Play will require app updates to have targetSdk 29+ from 2 November 2020 https://developer.android.com/distribute/best-practices/develop/target-sdk#pre10 , so the plugin will become essentially unusable if the bug is not fixed

**Comment by sawankumarbundelkhandi** [comment]
I will update the target soon.

**Comment by Hesamedin** [comment]
@sawankumarbundelkhandi Please add the solution, that has mentioned in your link,  to the Readme file ASAP! I stuck in this issue and that line helped me. Thank you.

```
  <application android:requestLegacyExternalStorage="true" ... >
```

**Comment by sawankumarbundelkhandi** [comment]
@Hesamedin I have added this tag in the plugin AppManifest.xaml and updated the targetSDK to 30.

**Comment by sawankumarbundelkhandi** [comment]
closing this as it's very similar to - https://github.com/sawankumarbundelkhandi/edge_detection/issues/28
