### ISSUE TITLE
Gradle task 'assembleDebug' FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by davidmarogy** [sawankumarbundelkhandi/edge_detection#42]
Hello,

i tried using the demo plugin in a new Flutter Project. Unfortunaly if i run my project i always get the error :

Running Gradle task 'assembleDebug'...
e: /home/dave/.pub-cache/hosted/pub.dartlang.org/edge_detection-1.0.5/android/src/main/kotlin/com/sample/edgedetection/scan/ScanPresenter.kt: (39, 1): Class 'ScanPresenter' is not abstract and does not implement abstract member public abstract fun surfaceCreated(@NonNull p0: SurfaceHolder): Unit defined in android.view.SurfaceHolder.Callback
e: /home/dave/.pub-cache/hosted/pub.dartlang.org/edge_detection-1.0.5/android/src/main/kotlin/com/sample/edgedetection/scan/ScanPresenter.kt: (143, 5): 'surfaceCreated' overrides nothing
e: /home/dave/.pub-cache/hosted/pub.dartlang.org/edge_detection-1.0.5/android/src/main/kotlin/com/sample/edgedetection/scan/ScanPresenter.kt: (147, 5): 'surfaceChanged' overrides nothing
e: /home/dave/.pub-cache/hosted/pub.dartlang.org/edge_detection-1.0.5/android/src/main/kotlin/com/sample/edgedetection/scan/ScanPresenter.kt: (151, 5): 'surfaceDestroyed' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':edge_detection:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Exception: Gradle task assembleDebug failed with exit code 1

It seems that some interfaces changed and the older ones are deprecated. Is it possible to change them? Also i tried running the plugin without my project, this worked but i got a warning : 
Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project.

Would be nice if this could be fixed.

**Comment by davidmarogy** [comment]
Well i found out that the problem was the gradle plugin. My gradle plugin for my project was 4.1.0 and in the example it was 3.5. No it is building correctly but neverless it is deprecated. Would be nice to have an fix to use it also on the newest gradle version.

**Comment by sawankumarbundelkhandi** [comment]
I have updated the compileVersionSdk and Gradle version.

Thanks for reporting it.
