### ISSUE TITLE
"saveAttributeDataForStyleable" static method not found

### ISSUE THREAD

**Issue by Appstute-Prerna** [sawankumarbundelkhandi/edge_detection#43]
When I initiate edge_detection plugin app crashes showing following error:

 java.lang.NoSuchMethodError: No static method saveAttributeDataForStyleable(Landroid/view/View;Landroid/content/Context;[ILandroid/util/AttributeSet;Landroid/content/res/TypedArray;II)V in class Landroidx/core/view/ViewCompat; or its super classes (declaration of 'androidx.core.view.ViewCompat' appears in /data/app/com.smartmd.messaging.dev-Ufcnw2cak6RG1BBZHLm2Iw==/base.apk)
E/AndroidRuntime(15727): 	at androidx.appcompat.widget.AppCompatBackgroundHelper.loadFromAttributes(AppCompatBackgroundHelper.java:51)
E/AndroidRuntime(15727): 	at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:79)
E/AndroidRuntime(15727): 	at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:69)
E/AndroidRuntime(15727): 	at androidx.appcompat.app.AppCompatViewInflater.createImageView(AppCompatViewInflater.java:199)
E/AndroidRuntime(15727): 	at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:119)
E/AndroidRuntime(15727): 	at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1551)
E/AndroidRuntime(15727): 	at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1602)
E/AndroidRuntime(15727): 	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1061)
E/AndroidRuntime(15727): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
E/AndroidRuntime(15727): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
E/AndroidRuntime(15727): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
E/AndroidRuntime(15727): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
E/AndroidRuntime(15727): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
E/AndroidRuntime(15727): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
E/AndroidRuntime(15727): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
E/AndroidRuntime(15727): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
E/AndroidRuntime(15727): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
E/AndroidRuntime(15727): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
E/AndroidRuntime(15727): 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
E/AndroidRuntime(15727): 	at com.sample.edgedetection.base.BaseActivity.onCreate(BaseActivity.kt:13)
E/AndroidRuntime(15727): 	at android.app.Activity.performCreate(Activity.java:7957)
E/AndroidRuntime(15727): 	at android.app.Activity.performCreate(Activity.java:7946)
E/AndroidRuntime(15727): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
E/AndroidRuntime(15727): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3530)
E/AndroidRuntime(15727): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3707)
E/AndroidRuntime(15727): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
E/AndroidRuntime(15727): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(15727): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(15727): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2220)
E/AndroidRuntime(15727): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(15727): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(15727): 	at android.app.ActivityThread.main(ActivityThread.java:8019)
E/AndroidRuntime(15727): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15727): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(15727): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

App Gradle:

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '6'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.2.1'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'

android {
    compileSdkVersion 29

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId "com.smartmd.messaging"
        minSdkVersion 26
        targetSdkVersion 29
        multiDexEnabled true
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        //ndk.abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'
    }

    buildTypes {
        release {
            //signingConfig signingConfigs.release
           // minifyEnabled true
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

            ndk {
                abiFilters 'armeabi-v7a', "arm64-v8a"
            }
        }

        debug {
            minifyEnabled false
            useProguard false

//            ndk {
//                abiFilters 'armeabi-v7a', "arm64-v8a"
//            }
        }
    }

    flavorDimensions "flavors"

    productFlavors {
        development {
            dimension "flavors"
            applicationIdSuffix ".dev"
            versionName "5.3.5"
            versionCode 157
        }
        production {
            dimension "flavors"
            versionName "5.3.0"
            versionCode 133
        }
        lilydev {
            dimension "flavors"
            applicationId "com.smartmd.lily.dev"
            versionName "5.3.5"
            versionCode 157
        }
        lilyprod {
            dimension "flavors"
            applicationId "com.smartmd.lily"
            versionName "5.0.2"
            versionCode 134
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation 'com.android.support:multidex:1.0.3' // use latest version
    implementation 'com.pubnub:pubnub-gson:4.29.2'
    implementation 'com.google.code.gson:gson:2.8.6'
    implementation 'com.google.firebase:firebase-core:18.0.0'

    //implementation 'com.google.firebase:firebase-auth:18.1.0'
    implementation 'com.google.firebase:firebase-messaging:21.0.0'

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
    api 'com.github.davidmigloz:opencv-android-gradle-repo:3.3.0'
    
    implementation group: 'joda-time', name: 'joda-time', version: '2.9.9'
    //implementation 'com.crashlytics.sdk.android:crashlytics:2.10.1'

    // Add the Firebase Crashlytics SDK.
    implementation 'com.google.firebase:firebase-crashlytics:17.3.0'

    // Recommended: Add the Google Analytics SDK.
    implementation 'com.google.firebase:firebase-analytics:18.0.0'

    implementation 'org.jsoup:jsoup:1.9.1'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'

//apply plugin: 'io.fabric'

**Comment by sawankumarbundelkhandi** [comment]
Do you think this will fix your issue?

https://github.com/RevenueCat/purchases-flutter/issues/117#issuecomment-732325386

**Comment by sawankumarbundelkhandi** [comment]
@Appstute-Prerna is it working now?

**Comment by Appstute-Prerna** [comment]
Yes
