### ISSUE TITLE
Add support for Flutter 2.0

### ISSUE THREAD

**Issue by prashant-confidosoft** [sawankumarbundelkhandi/edge_detection#47]

**Comment by giapnhgc** [comment]
It work perfect in flutter 2.0.3

**Comment by espbee** [comment]
It does work fine. Beyond that, if you're looking for null safety, I just tried forking the package and running the migration tool myself. It made like four changes and it's perfect.

**Comment by sawankumarbundelkhandi** [comment]
I just installed it on a new project and I am running the latest beta version of flutter and it's working 

![image](https://user-images.githubusercontent.com/10863510/117776469-3ff84200-b259-11eb-9188-d982f88d74c5.png)

![image](https://user-images.githubusercontent.com/10863510/117776576-5acab680-b259-11eb-856f-9d4d3a687188.png)

**Comment by sawankumarbundelkhandi** [comment]
@espbee can you do a PR if you have successfully migrated to null safety?

**Comment by espbee** [comment]
@sawankumarbundelkhandi done, but when you look at it you'll see how extremely modest the changes really are. i did run it on my physical iPhone and it works great.

what seems to remain also though is updating the android classes, like this: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects 

i looked at it real quick, but haven't done that before and don't have time to try and really do it for a moment. if you want help with that i'm happy to give it a shot when i have a chance, prob next week-- or if someone who's done it and can do it real quick wants to step in--

anyway thanks for making this to begin with, it's helpful.

**Comment by sawankumarbundelkhandi** [comment]
@espbee I have merged the code from your master branch to this project master with this PR - https://github.com/sawankumarbundelkhandi/edge_detection/pull/48
