### ISSUE TITLE
The apk size is large when is forked

### ISSUE THREAD

**Issue by gamalielCastro** [sawankumarbundelkhandi/edge_detection#51]
Hi, I forked this repo for do some changes of color, assets, etc.
But when I added my repo to the pubspec.yaml file and build the apk, the size was around 100MB
then I deleted jniLibs\x86 and jniLibs\x86_64 folders and the size reduce considerably to 50MB.

What another folder is necesary delete for final release?

**Comment by sawankumarbundelkhandi** [comment]
@zarulizham it's here - edge_detection/android/src/main/jniLibs

**Comment by sawankumarbundelkhandi** [comment]
@gamalielCastro you can delete all the folders except armeabi-v7a and arm64-v8a. These are the only two ABIs I use while publishing the plugin.

https://android.stackexchange.com/a/213663

When running on an emulator you have to keep the x86 or x86_64, based on your emulator architecture.
