### ISSUE TITLE
[Android]'minBy((T) -> R): T?' is an error. Use minByOrNull instead.

### ISSUE THREAD

**Issue by Osmancn** [sawankumarbundelkhandi/edge_detection#58]
e: /Users/osmancan/flutter/.pub-cache/hosted/pub.dartlang.org/edge_detection-1.0.6/android/src/main/kotlin/com/sample/edgedetection/processor/PaperProcessor.kt: (139, 21): Using 'minBy((T) -> R): T?' is an error. Use minByOrNull instead.
e: /Users/osmancan/flutter/.pub-cache/hosted/pub.dartlang.org/edge_detection-1.0.6/android/src/main/kotlin/com/sample/edgedetection/processor/PaperProcessor.kt: (140, 21): Using 'minBy((T) -> R): T?' is an error. Use minByOrNull instead.
e: /Users/osmancan/flutter/.pub-cache/hosted/pub.dartlang.org/edge_detection-1.0.6/android/src/main/kotlin/com/sample/edgedetection/processor/PaperProcessor.kt: (141, 21): Using 'maxBy((T) -> R): T?' is an error. Use maxByOrNull instead.
e: /Users/osmancan/flutter/.pub-cache/hosted/pub.dartlang.org/edge_detection-1.0.6/android/src/main/kotlin/com/sample/edgedetection/processor/PaperProcessor.kt: (142, 21): Using 'maxBy((T) -> R): T?' is an error. Use maxByOrNull instead.
e: /Users/osmancan/flutter/.pub-cache/hosted/pub.dartlang.org/edge_detection-1.0.6/android/src/main/kotlin/com/sample/edgedetection/scan/ScanPresenter.kt: (260, 53): Using 'maxBy((T) -> R): T?' is an error. Use maxByOrNull instead.
e: /Users/osmancan/flutter/.pub-cache/hosted/pub.dartlang.org/edge_detection-1.0.6/android/src/main/kotlin/com/sample/edgedetection/view/PaperRectangle.kt: (141, 29): Using 'minBy((T) -> R): T?' is an error. Use minByOrNull instead.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':edge_detection:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 31s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by GreyCardinalRus** [comment]
Me too.
How fix it?

**Comment by Osmancn** [comment]
> Me too. How fix it?

İ didnt
