### ISSUE TITLE
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'edge_detection' is using version 1.2.30.

### ISSUE THREAD

**Issue by SimonPeter1909** [sawankumarbundelkhandi/edge_detection#6]
While Running the Project I got this Error. 'The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'edge_detection' is using version 1.2.30.'. I have Changed the kotlin version to 1.2.30 but I got the Error that 'The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project android is using version 1.2.30.'

How can I solve the Error?

**Comment by SimonPeter1909** [comment]
I have changed the version to 1.2.51 in .pub-chache inside flutter sdk. So the error has been cleared. I'm closing the issue.

**Comment by firatcetiner** [comment]
Same issue occuring as version with version '1.2.51' and changing it to '1.3.0' (which is the minimum supported version by Gradle in the moment) does not resolve the issue.
