### ISSUE TITLE
The plugin `edge_detection` uses a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by Ryanmtate** [sawankumarbundelkhandi/edge_detection#61]
Received the following error while building:

> The plugin `edge_detection` uses a deprecated version of the Android embedding. To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs. If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

Appears to cause the application to fail when saving the cropped image. Resulting in the error:

> Caused by: java.io.FileNotFoundException: /storage/emulated/0/smart_scanner/crop_4543.jpeg: open failed: EPERM (Operation not permitted)

Can provide full trace if needed.

**Comment by jhubar** [comment]
I think this issues was solved (see https://github.com/sawankumarbundelkhandi/edge_detection/issues/57). They soon be released in pub dev
