### ISSUE TITLE
Layout failed on iOS 15

### ISSUE THREAD

**Issue by Zhanerkeb** [sawankumarbundelkhandi/edge_detection#65]

**Comment by sawankumarbundelkhandi** [comment]
@Zhanerkeb  can you add some screenshot?

**Comment by sawankumarbundelkhandi** [comment]
@Zhanerkeb I have no idea where it's going wrong for you. 
Closing this issue as it's working as expected (screenshots below)

![1](https://user-images.githubusercontent.com/10863510/141111731-ee656d38-64ee-4971-8886-0fccda713f33.png)
![2](https://user-images.githubusercontent.com/10863510/141111738-87d3af1a-d3a5-4452-b344-95589a336522.png)
![3](https://user-images.githubusercontent.com/10863510/141111744-d117d3eb-a5b1-4b03-b200-329d7ce15166.png)
![4](https://user-images.githubusercontent.com/10863510/141111746-8cdfbc3d-39d9-4dd3-8ac6-0bc41cf9584f.png)
![5](https://user-images.githubusercontent.com/10863510/141111748-8695495d-70bb-4650-91f4-ec4b9f722560.png)

**Comment by ImaThanusan** [comment]
Hi, @sawankumarbundelkhandi - many thanks for developing this great package 😊

Do you know if there is a solution for bottom of the Review Screen being cropped off (shown in your photo #4, issue #72)?

One workaround I can think of is to remove the bottom nav bar and turn background to black when calling the edge detection function

Is there a more elegant solution to this that you are aware of that may help? The main issue I'm facing is that the bottom nav bar can be interacted by the user, causing state to be lost if they navigate away from the current screen

Appreciate the help!

![141111746-8cdfbc3d-39d9-4dd3-8ac6-0bc41cf9584f](https://user-images.githubusercontent.com/37945195/153751225-d28bfa96-097f-45a2-ae0e-d665f4a8be9d.png)

**Comment by sawankumarbundelkhandi** [comment]
@Zhanerkeb @ImaThanusan it's issue with the WeScan plugin itself - https://github.com/WeTransfer/WeScan/issues/328
