### ISSUE TITLE
Small user test result: User guidance missing at crop step

### ISSUE THREAD

**Issue by maltemedocs** [sawankumarbundelkhandi/edge_detection#67]
I'm currently evaluating edge_detection for a proprietary app and had the chance to do a small user test, running the current git version (as necessary to be compatible with flutter 2.3.2).

The plugin overall worked great. But this step was problematic:

![Screenshot_1635499534](https://user-images.githubusercontent.com/71251334/139412469-16d11d96-f08f-42e2-89e3-47956cb4e7a1.png)

The users were uncertain what to click on here to continue, something I also observed with myself. The crop icon at the right is unclear, and also not more prominent than the back button. To my eyes it even looks disabled, as it seems to be lightly grey.

The readme is showing a text button at that position instead, which I would expect to work better. Alternatively there could be a floating action button, at least on Android. Ideally this UI should be a bit configurable.

If PRs are welcome for this I could invest some time to make some small UI changes for that step and send that in as PR, assuming the plugin controls these views directly?

**Comment by sawankumarbundelkhandi** [comment]
@maltemedocs PR are welcomed. You can add a FAB on the bottom center and use the same listener as for the crop icon.
