### ISSUE TITLE
Using edge_detection increasing the app size by a lot

### ISSUE THREAD

**Issue by XpertWebApp** [sawankumarbundelkhandi/edge_detection#70]
I am using edge_detection and google_ml_kit library in my project . Increasing the app size 60 to 120 mb . :(

**Comment by sawankumarbundelkhandi** [comment]
Can you try using ABIs Filters? - https://developer.android.com/ndk/guides/abis#gc

**Comment by sawankumarbundelkhandi** [comment]
Also, is your issue similar to this? https://github.com/sawankumarbundelkhandi/edge_detection/issues/51

**Comment by sawankumarbundelkhandi** [comment]
I have decreased the plugin size by just pushing armeabi-v7a ABI

**Comment by sawankumarbundelkhandi** [comment]
I have again added armeabi-v8a to fix - https://github.com/sawankumarbundelkhandi/edge_detection/issues/85

**Comment by sawankumarbundelkhandi** [comment]
@XpertWebApp try directly from Github in pubspec.yaml and let me know if it help in size at all. I have just now deleted all jni files and using aar for open cv.

edge_detection: 
git: https://github.com/sawankumarbundelkhandi/edge_detection.git

**Comment by sawankumarbundelkhandi** [comment]
it's available now here - https://pub.dev/packages/edge_detection/versions/1.1.3
