### ISSUE TITLE
Any chance you might update WeScan to its latest version?

### ISSUE THREAD

**Issue by espbee** [sawankumarbundelkhandi/edge_detection#76]
@sawankumarbundelkhandi  ,
hi again thanks for this lib, it's extremely helpful. 

I get XCode warnings about functions in WeScan and I think this lib is using an older-than-current version? Is it possible that you'd be able to update?

Thanks.

**Comment by sawankumarbundelkhandi** [comment]
I am already using the latest version of the WeScan SDK. Check here - https://github.com/sawankumarbundelkhandi/edge_detection/blob/master/ios/edge_detection.podspec

**Comment by espbee** [comment]
My fault, misread, forgive the interruption. Hope all's well.
