### ISSUE TITLE
How to crop an image in original image ratio from the gallery in Android

### ISSUE THREAD

**Issue by hypernova1** [sawankumarbundelkhandi/edge_detection#77]
@sawankumarbundelkhandi 

hello.

sorry my English is not good...

I've been trying to crop image in my project. (Android!!)

As far as I know, default function of edge_detection works only for smartphone device ratio.

But I want to get photos from photo library and crop images in original image ratio such as 16:9, not device ratio.

How can I do it? Please help me........

**Comment by mev007** [comment]
@hypernova1 Did you find an answer?
