### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "libopencv_java3.so" not found

### ISSUE THREAD

**Issue by akash29071994** [sawankumarbundelkhandi/edge_detection#85]

**Comment by sawankumarbundelkhandi** [comment]
@akash29071994 are you using the plugin from pub.dev version or directly from github? which phone are you using?

**Comment by kairon007** [comment]
Getting the same issue as above

**Comment by RamboFisk** [comment]
> @akash29071994 are you using the plugin from pub.dev version or directly from github? which phone are you using?

Had the same issue when using the pub.dev version. It seems to work if you put the github repo directly as source

**Comment by sawankumarbundelkhandi** [comment]
@akash29071994 @kairon007 @RamboFisk  let me check the issue. I am not sure of what's happening

**Comment by sawankumarbundelkhandi** [comment]
I have fixed the issue. Please try edge_detection: ^1.0.9 from pub.dev
