### ISSUE TITLE
OpenCV error: Cannot load info library for OpenCV

### ISSUE THREAD

**Issue by sinanhaci** [sawankumarbundelkhandi/edge_detection#88]
Hi,

I'm getting this error on the Android side, do you have a solution for this?

Flutter version: 3.0.2,
Package version: 1.0.9,
Platform: Android

`
D/OpenCV/StaticHelper(20853): Trying to get library list
E/OpenCV/StaticHelper(20853): OpenCV error: Cannot load info library for OpenCV
D/OpenCV/StaticHelper(20853): Library list: ""
D/OpenCV/StaticHelper(20853): First attempt to load libs
D/OpenCV/StaticHelper(20853): Trying to init OpenCV libs
D/OpenCV/StaticHelper(20853): Trying to load library opencv_java3
D/OpenCV/StaticHelper(20853): Cannot load library "opencv_java3"
W/System.err(20853): java.lang.UnsatisfiedLinkError: dlopen failed: library "libopencv_java3.so" not found
W/System.err(20853): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
W/System.err(20853): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
W/System.err(20853): 	at java.lang.System.loadLibrary(System.java:1664)
W/System.err(20853): 	at org.opencv.android.StaticHelper.loadLibrary(StaticHelper.java:64)
W/System.err(20853): 	at org.opencv.android.StaticHelper.initOpenCVLibs(StaticHelper.java:95)
W/System.err(20853): 	at org.opencv.android.StaticHelper.initOpenCV(StaticHelper.java:39)
W/System.err(20853): 	at org.opencv.android.OpenCVLoader.initDebug(OpenCVLoader.java:102)
W/System.err(20853): 	at com.sample.edgedetection.scan.ScanActivity.prepare(ScanActivity.kt:48)
W/System.err(20853): 	at com.sample.edgedetection.base.BaseActivity.onCreate(BaseActivity.kt:16)
W/System.err(20853): 	at android.app.Activity.performCreate(Activity.java:7994)
W/System.err(20853): 	at android.app.Activity.performCreate(Activity.java:7978)
W/System.err(20853): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
W/System.err(20853): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
W/System.err(20853): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
W/System.err(20853): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
W/System.err(20853): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
W/System.err(20853): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
W/System.err(20853): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
W/System.err(20853): 	at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err(20853): 	at android.os.Looper.loop(Looper.java:223)
W/System.err(20853): 	at android.app.ActivityThread.main(ActivityThread.java:7656)

`

**Comment by sawankumarbundelkhandi** [comment]
Can you check similarly reported issues here? - https://github.com/sawankumarbundelkhandi/edge_detection/issues?q=is%3Aissue+OpenCV+error%3A+Cannot+load+info+library+for+OpenCV

Is this a debug run or release run issue?

**Comment by sinanhaci** [comment]
Yes, actually I checked yesterday before reporting the issue but it didn't work. Now it worked when I tried it on a different real device. Thank you
