### ISSUE TITLE
Can i cut only in rectangular shape?

### ISSUE THREAD

**Issue by alionurozdemir** [sawankumarbundelkhandi/edge_detection#93]
Hi, Can you only select rectangular? (4 selection points)
So can I add multiple points?
How do I do this? (Note: I want to cut a profile photo.)

Thanks.

**Comment by sawankumarbundelkhandi** [comment]
Yes, the plugin only supports 4 edges. Also, this issue seems duplicate of https://github.com/sawankumarbundelkhandi/edge_detection/issues/27
