### ISSUE TITLE
File does not exist

### ISSUE THREAD

**Issue by federicolucca** [sawankumarbundelkhandi/edge_detection#94]
Hi All,

i have this lines of code 

EdgeDetection.useInternalStorage(true);
String? imagePath = await EdgeDetection.detectEdge;

that give me to the log "File does not exist"

someone can help?

**Comment by rsanjuan87** [comment]
platform? ios?
I think this was fixed al ready
https://github.com/sawankumarbundelkhandi/edge_detection/pull/127
